In [17]:
# practice before the final project

In [18]:
from tensorflow.keras.preprocessing.text import one_hot

In [19]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [20]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [21]:
## Define the vocabulary size
voc_size=10000

In [22]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [23]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1058, 6393, 3690, 9373],
 [1058, 6393, 3690, 7949],
 [1058, 3647, 3690, 6494],
 [6968, 8582, 8251, 8202, 2303],
 [6968, 8582, 8251, 8202, 9940],
 [1756, 1058, 5506, 3690, 7369],
 [3027, 3729, 3777, 8202]]

In [24]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [25]:
import numpy as np

In [26]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1058 6393 3690 9373]
 [   0    0    0    0 1058 6393 3690 7949]
 [   0    0    0    0 1058 3647 3690 6494]
 [   0    0    0 6968 8582 8251 8202 2303]
 [   0    0    0 6968 8582 8251 8202 9940]
 [   0    0    0 1756 1058 5506 3690 7369]
 [   0    0    0    0 3027 3729 3777 8202]]


In [27]:
## feature representation
dim=10

In [28]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [29]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [30]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step


array([[[-0.04451985, -0.00168514,  0.03745398,  0.02437815,
          0.00171192, -0.02238457, -0.00371403,  0.02089551,
          0.0029781 ,  0.00240158],
        [-0.04451985, -0.00168514,  0.03745398,  0.02437815,
          0.00171192, -0.02238457, -0.00371403,  0.02089551,
          0.0029781 ,  0.00240158],
        [-0.04451985, -0.00168514,  0.03745398,  0.02437815,
          0.00171192, -0.02238457, -0.00371403,  0.02089551,
          0.0029781 ,  0.00240158],
        [-0.04451985, -0.00168514,  0.03745398,  0.02437815,
          0.00171192, -0.02238457, -0.00371403,  0.02089551,
          0.0029781 ,  0.00240158],
        [-0.0256569 ,  0.00978075,  0.02410126,  0.00530424,
         -0.02313348, -0.00033034, -0.0471057 , -0.04646833,
          0.02189584, -0.02795571],
        [ 0.01246738,  0.04395634, -0.03290125, -0.0405112 ,
          0.00647908, -0.00185985,  0.02656095,  0.00493626,
          0.04232606,  0.0476278 ],
        [-0.04865389,  0.02355728,  0.02672435, -0.0

In [31]:
embedded_docs[0]

array([   0,    0,    0,    0, 1058, 6393, 3690, 9373], dtype=int32)

In [32]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>